sudo: required
dist: trusty
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly
  - nightly

install:
  - composer self-update
  - composer install --prefer-source --no-interaction

notifications:
  irc: "irc.freenode.org#nextflow.dev"
  email: false
  
matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: hhvm
    - php: hhvm-nightly
    - php: nightly
