language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install --dev --prefer-source

notifications:
  irc: "irc.freenode.org#nextflow.dev"
  email: false
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
